# Generated by Django 4.2 on 2023-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
