# Generated by Django 4.2 on 2023-04-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0005_alter_usuario_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="celular",
            field=models.IntegerField(null=True),
        ),
    ]
