# Generated by Django 4.2 on 2023-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0006_usuario_celular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="celular",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
