# Generated by Django 4.2 on 2023-04-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0007_alter_usuario_celular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="vencimiento",
            field=models.DateField(
                blank=True,
                help_text="Si no es especificado será dentro de 30 dias",
                null=True,
            ),
        ),
    ]
