# Generated by Django 4.1.3 on 2023-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0008_alter_usuario_vencimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="sexo",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=1
            ),
        ),
    ]
