# Generated by Django 4.1.3 on 2023-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0009_alter_usuario_sexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="sexo",
            field=models.CharField(
                choices=[("Femenino", "Femenino"), ("Masculino", "Masculino")],
                max_length=10,
            ),
        ),
    ]
