# Generated by Django 4.2 on 2023-05-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0010_alter_usuario_sexo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sexo",
        ),
    ]
