# Generated by Django 4.2.1 on 2023-05-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0011_delete_sexo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.DateField(auto_now=True)),
                ("hora", models.TimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="power_app.usuario",
                    ),
                ),
            ],
        ),
    ]
