# Generated by Django 4.2 on 2023-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0014_asistencia_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
