# Generated by Django 4.2 on 2023-08-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("power_app", "0015_alter_usuario_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="celular",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
